{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1d458d3e-1b5f-4ee6-99e6-dd01cc8654eb",
   "metadata": {},
   "source": [
    "# Example Script for the Senior Model\n",
    "\n",
    "This is the example script of the Senior model and is based on the previous exploration of the teacher, tutor, junior  script. Note that in order to run this Notebook, ray needs to be working !"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import grid2op\n",
    "from lightsim2grid import LightSimBackend\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "import ray\n",
    "import ray.tune as tune\n",
    "import tensorflow as tf\n",
    "from ray.tune.schedulers import PopulationBasedTraining\n",
    "from ray.rllib.models import ModelCatalog\n",
    "import pickle\n",
    "import random\n",
    "import json\n",
    "example_path = os.getcwd()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1e1a8e91-ea0b-47a0-a375-9af880424624",
   "metadata": {},
   "source": [
    "Again we test the Grid2Op Environment. Additionally, we already init() ray"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3fd3f98e-a3e8-4ae7-8403-e5944a77a56f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c:\\Users\\thoma\\MA\\curriculumagent\\jupyter_notebooks\\data\\training_data_track1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\n",
      "  warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\n",
      "  warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: divide by zero encountered in divide\n",
      "  p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: invalid value encountered in multiply\n",
      "  p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\n",
      "  q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\n",
      "  q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "2024-05-06 15:23:40,518\tINFO worker.py:1627 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32m127.0.0.1:8265 \u001b[39m\u001b[22m\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "    <div style=\"margin-left: 50px;display: flex;flex-direction: row;align-items: center\">\n",
       "        <h3 style=\"color: var(--jp-ui-font-color0)\">Ray</h3>\n",
       "        <svg version=\"1.1\" id=\"ray\" width=\"3em\" viewBox=\"0 0 144.5 144.6\" style=\"margin-left: 3em;margin-right: 3em\">\n",
       "            <g id=\"layer-1\">\n",
       "                <path fill=\"#00a2e9\" class=\"st0\" d=\"M97.3,77.2c-3.8-1.1-6.2,0.9-8.3,5.1c-3.5,6.8-9.9,9.9-17.4,9.6S58,88.1,54.8,81.2c-1.4-3-3-4-6.3-4.1\n",
       "                    c-5.6-0.1-9.9,0.1-13.1,6.4c-3.8,7.6-13.6,10.2-21.8,7.6C5.2,88.4-0.4,80.5,0,71.7c0.1-8.4,5.7-15.8,13.8-18.2\n",
       "                    c8.4-2.6,17.5,0.7,22.3,8c1.3,1.9,1.3,5.2,3.6,5.6c3.9,0.6,8,0.2,12,0.2c1.8,0,1.9-1.6,2.4-2.8c3.5-7.8,9.7-11.8,18-11.9\n",
       "                    c8.2-0.1,14.4,3.9,17.8,11.4c1.3,2.8,2.9,3.6,5.7,3.3c1-0.1,2,0.1,3,0c2.8-0.5,6.4,1.7,8.1-2.7s-2.3-5.5-4.1-7.5\n",
       "                    c-5.1-5.7-10.9-10.8-16.1-16.3C84,38,81.9,37.1,78,38.3C66.7,42,56.2,35.7,53,24.1C50.3,14,57.3,2.8,67.7,0.5\n",
       "                    C78.4-2,89,4.7,91.5,15.3c0.1,0.3,0.1,0.5,0.2,0.8c0.7,3.4,0.7,6.9-0.8,9.8c-1.7,3.2-0.8,5,1.5,7.2c6.7,6.5,13.3,13,19.8,19.7\n",
       "                    c1.8,1.8,3,2.1,5.5,1.2c9.1-3.4,17.9-0.6,23.4,7c4.8,6.9,4.6,16.1-0.4,22.9c-5.4,7.2-14.2,9.9-23.1,6.5c-2.3-0.9-3.5-0.6-5.1,1.1\n",
       "                    c-6.7,6.9-13.6,13.7-20.5,20.4c-1.8,1.8-2.5,3.2-1.4,5.9c3.5,8.7,0.3,18.6-7.7,23.6c-7.9,5-18.2,3.8-24.8-2.9\n",
       "                    c-6.4-6.4-7.4-16.2-2.5-24.3c4.9-7.8,14.5-11,23.1-7.8c3,1.1,4.7,0.5,6.9-1.7C91.7,98.4,98,92.3,104.2,86c1.6-1.6,4.1-2.7,2.6-6.2\n",
       "                    c-1.4-3.3-3.8-2.5-6.2-2.6C99.8,77.2,98.9,77.2,97.3,77.2z M72.1,29.7c5.5,0.1,9.9-4.3,10-9.8c0-0.1,0-0.2,0-0.3\n",
       "                    C81.8,14,77,9.8,71.5,10.2c-5,0.3-9,4.2-9.3,9.2c-0.2,5.5,4,10.1,9.5,10.3C71.8,29.7,72,29.7,72.1,29.7z M72.3,62.3\n",
       "                    c-5.4-0.1-9.9,4.2-10.1,9.7c0,0.2,0,0.3,0,0.5c0.2,5.4,4.5,9.7,9.9,10c5.1,0.1,9.9-4.7,10.1-9.8c0.2-5.5-4-10-9.5-10.3\n",
       "                    C72.6,62.3,72.4,62.3,72.3,62.3z M115,72.5c0.1,5.4,4.5,9.7,9.8,9.9c5.6-0.2,10-4.8,10-10.4c-0.2-5.4-4.6-9.7-10-9.7\n",
       "                    c-5.3-0.1-9.8,4.2-9.9,9.5C115,72.1,115,72.3,115,72.5z M19.5,62.3c-5.4,0.1-9.8,4.4-10,9.8c-0.1,5.1,5.2,10.4,10.2,10.3\n",
       "                    c5.6-0.2,10-4.9,9.8-10.5c-0.1-5.4-4.5-9.7-9.9-9.6C19.6,62.3,19.5,62.3,19.5,62.3z M71.8,134.6c5.9,0.2,10.3-3.9,10.4-9.6\n",
       "                    c0.5-5.5-3.6-10.4-9.1-10.8c-5.5-0.5-10.4,3.6-10.8,9.1c0,0.5,0,0.9,0,1.4c-0.2,5.3,4,9.8,9.3,10\n",
       "                    C71.6,134.6,71.7,134.6,71.8,134.6z\"/>\n",
       "            </g>\n",
       "        </svg>\n",
       "        <table>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Python version:</b></td>\n",
       "                <td style=\"text-align: left\"><b>3.9.19</b></td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                <td style=\"text-align: left\"><b>Ray version:</b></td>\n",
       "                <td style=\"text-align: left\"><b> 2.5.1</b></td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "    <td style=\"text-align: left\"><b>Dashboard:</b></td>\n",
       "    <td style=\"text-align: left\"><b><a href=\"http://127.0.0.1:8265\" target=\"_blank\">http://127.0.0.1:8265</a></b></td>\n",
       "</tr>\n",
       "\n",
       "        </table>\n",
       "    </div>\n",
       "</div>\n"
      ],
      "text/plain": [
       "RayContext(dashboard_url='127.0.0.1:8265', python_version='3.9.19', ray_version='2.5.1', ray_commit='a03efd9931128d387649dd48b0e4864b43d3bfb4', address_info={'node_ip_address': '127.0.0.1', 'raylet_ip_address': '127.0.0.1', 'redis_address': None, 'object_store_address': 'tcp://127.0.0.1:58368', 'raylet_socket_name': 'tcp://127.0.0.1:58845', 'webui_url': '127.0.0.1:8265', 'session_dir': 'C:\\\\Users\\\\thoma\\\\AppData\\\\Local\\\\Temp\\\\ray\\\\session_2024-05-06_15-23-36_488961_10556', 'metrics_export_port': 51729, 'gcs_address': '127.0.0.1:63028', 'address': '127.0.0.1:63028', 'dashboard_agent_listen_port': 52365, 'node_id': '36a6ca80dab37cf0ec97d12a4dbb7938cd27923aca5cdbec83fb0840'})"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[33m(raylet)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\dashboard\\modules\\reporter\\reporter_agent.py:56: UserWarning: `gpustat` package is not installed. GPU monitoring is not available. To have full functionality of the dashboard please install `pip install ray[default]`.)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   warnings.warn(\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:33:58,594\tWARNING algorithm_config.py:643 -- Cannot create PPOConfig from given `config_dict`! Property __stdout_file__ not supported.\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:33:58,596\tINFO algorithm.py:536 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=9496)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=9496)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=9496)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=9496)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=7928)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19080)\u001b[0m 2024-05-06 15:34:52,028\tWARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m 2024-05-06 15:34:52,549\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=24504, ip=127.0.0.1, actor_id=15e95dac240e6f578a026d4801000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001C9751A0340>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 738, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     self._build_policy_map(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     new_policy = create_policy_for_framework(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\ppo\\ppo_torch_policy.py\", line 49, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     TorchPolicyV2.__init__(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     model = ModelCatalog.get_model_v2(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     model_cls = _global_registry.get(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=24504)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16736)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\u001b[32m [repeated 14x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16736)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m 2024-05-06 15:34:58,078\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16072, ip=127.0.0.1, actor_id=e3f75364a549b7b974f694fc01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D7EC7EF310>)\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     return method(__ray_actor, *args, **kwargs)\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\u001b[32m [repeated 27x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     return method(self, *_args, **_kwargs)\u001b[32m [repeated 27x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\u001b[32m [repeated 27x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     self._build_policy_map(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     new_policy = create_policy_for_framework(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     TorchPolicyV2.__init__(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     model = ModelCatalog.get_model_v2(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     model_cls = _global_registry.get(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m     raise ValueError(\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=16072)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,591\tERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19080, ip=127.0.0.1, actor_id=881f7bf2122de0001353ec3701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000206C20E02B0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,597\tERROR actor_manager.py:507 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=7928, ip=127.0.0.1, actor_id=1e92eed53d616a0578db826c01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001B071AF7310>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,598\tERROR actor_manager.py:507 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=15432, ip=127.0.0.1, actor_id=f06e0504fef1eada607b35ef01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000242EDC302B0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,599\tERROR actor_manager.py:507 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=9496, ip=127.0.0.1, actor_id=8cd402bbb4079bdb2812906c01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F1F438F250>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,600\tERROR actor_manager.py:507 -- Ray error, taking actor 5 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=24504, ip=127.0.0.1, actor_id=15e95dac240e6f578a026d4801000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001C9751A0340>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,601\tERROR actor_manager.py:507 -- Ray error, taking actor 6 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=31916, ip=127.0.0.1, actor_id=dedd56b2b1a0779367e414b001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000293B12372E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,602\tERROR actor_manager.py:507 -- Ray error, taking actor 7 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=17712, ip=127.0.0.1, actor_id=2effe7cc21355faf8d1da6f701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000027B4155F250>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,603\tERROR actor_manager.py:507 -- Ray error, taking actor 8 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16736, ip=127.0.0.1, actor_id=2696f46fe90412c5d5c805d201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001B2F69F02E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,603\tERROR actor_manager.py:507 -- Ray error, taking actor 9 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19572, ip=127.0.0.1, actor_id=f4db09fb1e6fbae8d4f8136601000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000013D404EF2E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,604\tERROR actor_manager.py:507 -- Ray error, taking actor 10 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=24096, ip=127.0.0.1, actor_id=d2b0ac5f11fca950f02006b701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000178C59C02E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,604\tERROR actor_manager.py:507 -- Ray error, taking actor 11 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=28648, ip=127.0.0.1, actor_id=767c376e95a60aa5f82f525e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000019E8DD30250>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,604\tERROR actor_manager.py:507 -- Ray error, taking actor 12 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=20424, ip=127.0.0.1, actor_id=c5a10592e28e150701edd17e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002177A3C8340>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,605\tERROR actor_manager.py:507 -- Ray error, taking actor 13 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=30524, ip=127.0.0.1, actor_id=fb1626efb0660ab49042f92901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000018F76CE7340>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,605\tERROR actor_manager.py:507 -- Ray error, taking actor 14 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=16072, ip=127.0.0.1, actor_id=e3f75364a549b7b974f694fc01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D7EC7EF310>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,606\tERROR actor_manager.py:507 -- Ray error, taking actor 15 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=29332, ip=127.0.0.1, actor_id=2295fdd3d4e7ad581ccdadc401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000029450AA02B0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20424)\u001b[0m 2024-05-06 15:35:02,675\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=20424, ip=127.0.0.1, actor_id=c5a10592e28e150701edd17e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002177A3C8340>)\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\u001b[32m [repeated 38x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return method(__ray_actor, *args, **kwargs)\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\u001b[32m [repeated 57x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return method(self, *_args, **_kwargs)\u001b[32m [repeated 57x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\u001b[32m [repeated 57x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self._build_policy_map(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     new_policy = create_policy_for_framework(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     TorchPolicyV2.__init__(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model = ModelCatalog.get_model_v2(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model_cls = _global_registry.get(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     raise ValueError(\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m 2024-05-06 15:35:03,644\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::PPO.__init__()\u001b[39m (pid=28980, ip=127.0.0.1, actor_id=b3aa8c21880e0ac687c1036101000000, repr=PPO)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 242, in _setup\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self.add_workers(\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 635, in add_workers\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     raise result.get()\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 488, in __fetch_result\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     result = ray.get(r)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     raise value\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19080, ip=127.0.0.1, actor_id=881f7bf2122de0001353ec3701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000206C20E02B0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m \u001b[36mray::PPO.__init__()\u001b[39m (pid=28980, ip=127.0.0.1, actor_id=b3aa8c21880e0ac687c1036101000000, repr=PPO)\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     super().__init__(\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self.setup(copy.deepcopy(self.config))\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 601, in setup\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self.workers = WorkerSet(\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     raise e.args[0].args[2]\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:35:25,024\tWARNING algorithm_config.py:643 -- Cannot create PPOConfig from given `config_dict`! Property __stdout_file__ not supported.\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:35:25,029\tINFO algorithm.py:536 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=15432)\u001b[0m 2024-05-06 15:35:25,029\tINFO algorithm.py:536 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\u001b[32m [repeated 8x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return method(__ray_actor, *args, **kwargs)\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\u001b[32m [repeated 8x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return method(self, *_args, **_kwargs)\u001b[32m [repeated 8x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 194, in __init__\u001b[32m [repeated 9x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     self._build_policy_map(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     new_policy = create_policy_for_framework(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m \u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model = ModelCatalog.get_model_v2(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     model_cls = _global_registry.get(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m     raise ValueError(\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=28980)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=19520)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m 2024-05-06 15:36:07,089\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=20812, ip=127.0.0.1, actor_id=a0c9f72b27d8674b02ddf13a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D959DA12E0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 738, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     self._build_policy_map(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     new_policy = create_policy_for_framework(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\ppo\\ppo_torch_policy.py\", line 49, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     TorchPolicyV2.__init__(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     model = ModelCatalog.get_model_v2(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     model_cls = _global_registry.get(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m     raise ValueError(\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=20812)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m 2024-05-06 15:36:07,041\tWARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\u001b[32m [repeated 14x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 28x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m 2024-05-06 15:36:12,682\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=21900, ip=127.0.0.1, actor_id=270ae72df27c84cb7d191e4d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A373A9F310>)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\u001b[32m [repeated 24x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     return method(__ray_actor, *args, **kwargs)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\u001b[32m [repeated 36x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     return method(self, *_args, **_kwargs)\u001b[32m [repeated 36x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\u001b[32m [repeated 36x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     self._build_policy_map(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     new_policy = create_policy_for_framework(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     TorchPolicyV2.__init__(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     model = ModelCatalog.get_model_v2(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     model_cls = _global_registry.get(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m     raise ValueError(\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21900)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\u001b[32m [repeated 12x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,878\tERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=21900, ip=127.0.0.1, actor_id=270ae72df27c84cb7d191e4d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A373A9F310>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,881\tERROR actor_manager.py:507 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=5832, ip=127.0.0.1, actor_id=f44bd1e2793215db333301ca01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000178720812E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,882\tERROR actor_manager.py:507 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19520, ip=127.0.0.1, actor_id=9871c0f3b141a27531ba574d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F779E0F340>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,883\tERROR actor_manager.py:507 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=9348, ip=127.0.0.1, actor_id=cfd736fc168f6e307c941e2a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002456A9A02B0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,885\tERROR actor_manager.py:507 -- Ray error, taking actor 5 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=30548, ip=127.0.0.1, actor_id=cb3eef5e5e2766eec30a456301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000021FDD7582E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,886\tERROR actor_manager.py:507 -- Ray error, taking actor 6 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=20812, ip=127.0.0.1, actor_id=a0c9f72b27d8674b02ddf13a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D959DA12E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,888\tERROR actor_manager.py:507 -- Ray error, taking actor 7 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=27148, ip=127.0.0.1, actor_id=e623d37805fb455bace52a2901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001DB96CE72E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,889\tERROR actor_manager.py:507 -- Ray error, taking actor 8 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=24588, ip=127.0.0.1, actor_id=b85f06899ca01794aa695d1301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000019EE42202E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,890\tERROR actor_manager.py:507 -- Ray error, taking actor 9 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19612, ip=127.0.0.1, actor_id=604d6f7505e93674b838ec7a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D34369F340>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,891\tERROR actor_manager.py:507 -- Ray error, taking actor 10 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=30300, ip=127.0.0.1, actor_id=8db52774d99651def97ca0da01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F3F2BB02B0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,892\tERROR actor_manager.py:507 -- Ray error, taking actor 11 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=4856, ip=127.0.0.1, actor_id=197c6e344cd890f4b274970e01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F7F57C01F0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,893\tERROR actor_manager.py:507 -- Ray error, taking actor 12 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=24508, ip=127.0.0.1, actor_id=c4584273d331d5a38e8b270201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000189BFBD7280>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,894\tERROR actor_manager.py:507 -- Ray error, taking actor 13 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=34148, ip=127.0.0.1, actor_id=dc94107b3f22c6423918301401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000022B71CC72E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,895\tERROR actor_manager.py:507 -- Ray error, taking actor 14 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=29164, ip=127.0.0.1, actor_id=f4eac1ab479371c9d75ccde201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000230E5D502E0>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,896\tERROR actor_manager.py:507 -- Ray error, taking actor 15 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=17860, ip=127.0.0.1, actor_id=e91bd7d87842bfdd7db05cfe01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000029DBE9E7190>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m 2024-05-06 15:36:13,923\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::PPO.__init__()\u001b[39m (pid=20508, ip=127.0.0.1, actor_id=b9b2c4d442914033cfa6895901000000, repr=PPO)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 242, in _setup\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     self.add_workers(\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 635, in add_workers\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     raise result.get()\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 488, in __fetch_result\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     result = ray.get(r)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     raise value\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=21900, ip=127.0.0.1, actor_id=270ae72df27c84cb7d191e4d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A373A9F310>)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m \u001b[36mray::PPO.__init__()\u001b[39m (pid=20508, ip=127.0.0.1, actor_id=b9b2c4d442914033cfa6895901000000, repr=PPO)\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     super().__init__(\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     self.setup(copy.deepcopy(self.config))\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 601, in setup\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     self.workers = WorkerSet(\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     raise e.args[0].args[2]\n",
      "\u001b[2m\u001b[36m(PPO pid=18988)\u001b[0m 2024-05-06 15:36:33,653\tWARNING algorithm_config.py:643 -- Cannot create PPOConfig from given `config_dict`! Property __stdout_file__ not supported.\n",
      "\u001b[2m\u001b[36m(PPO pid=18988)\u001b[0m 2024-05-06 15:36:33,656\tINFO algorithm.py:536 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=29164)\u001b[0m 2024-05-06 15:36:13,854\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=29164, ip=127.0.0.1, actor_id=f4eac1ab479371c9d75ccde201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000230E5D502E0>)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\u001b[32m [repeated 40x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     return method(__ray_actor, *args, **kwargs)\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\u001b[32m [repeated 56x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     return method(self, *_args, **_kwargs)\u001b[32m [repeated 56x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 194, in __init__\u001b[32m [repeated 57x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     self._update_policy_map(policy_dict=self.policy_dict)\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     self._build_policy_map(\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     new_policy = create_policy_for_framework(\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     return policy_class(observation_space, action_space, merged_config)\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m \u001b[32m [repeated 20x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     model, dist_class = self._init_model_and_dist_class()\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     model = ModelCatalog.get_model_v2(\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     model_cls = _global_registry.get(\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m   File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m     raise ValueError(\u001b[32m [repeated 18x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(PPO pid=20508)\u001b[0m ValueError: Registry value for rllib_model/binbinchen doesn't exist.\u001b[32m [repeated 19x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=21652)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\u001b[32m [repeated 13x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m   warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\u001b[32m [repeated 13x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\u001b[32m [repeated 13x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m   warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\u001b[32m [repeated 13x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\u001b[32m [repeated 26x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m   p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 26x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\u001b[32m [repeated 26x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=3884)\u001b[0m   q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\u001b[32m [repeated 26x across cluster]\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "backend = LightSimBackend()\n",
    "env_path = test_data_path = Path(example_path)/ \"data\" / \"training_data_track1\"\n",
    "print(env_path)\n",
    "env = grid2op.make(env_path, backend=backend)\n",
    "env.set_id(1)\n",
    "env.reset()\n",
    "env.chronics_handler.get_name()\n",
    "obs = env.get_obs()\n",
    "\n",
    "if ray.is_initialized:\n",
    "    ray.shutdown()\n",
    "ray.init()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ebfb0da1-0401-457f-aa41-f5c521d639dc",
   "metadata": {},
   "source": [
    "## Training based on the more complex Junior model.\n",
    "\n",
    "In this example, we show the implementation of the hyper-paramter optimized Junior model by using the\n",
    "```AdvancedCustomModel```. Note that  one can simply use the ```Grid2OpCustomModel``` if the simple Junior was trained."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8cb18b2b-f532-4b72-9667-783a7c253f45",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\sklearn\\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator MinMaxScaler from version 1.2.2 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n",
      "https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "with open(Path(example_path) / \"data\" /'scaler_junior.pkl', \"rb\") as fp:   #Pickling\n",
    "    scaler = pickle.load(fp)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "Under consideration that ray has sometimes trouble finding the scaler with one of its workers, we advice to use the ```ray.put()``` and ```ray.get()``` option."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ade5b6f1-7b5c-4032-a787-9e36086fe5f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "ray_scal = ray.put(scaler)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "Now we have to initialize both the config of the environment, as well as of the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dce058d8-d0b8-4f55-85d3-9e93e53549e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "action_path1 = Path(example_path) / \"data\" / \"actionspace_nminus1.npy\"\n",
    "action_path2 = Path(example_path) / \"data\" / \"actionspace_tuples.npy\"\n",
    "action_set = [action_path1, action_path2]\n",
    "model_path = Path(example_path) / \"data\" / \"junior_model\"\n",
    "data_path = Path(example_path) / \"data\"  / \"junior_experience\"\n",
    "target = Path(example_path) / \"data\" / \"junior_model\"/ \"hyperparam\"\n",
    "hyperparam_path = Path(example_path) / \"data\" / 'junior_best_params.json'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d8c115a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'activation': 'relu', 'batchsize': 256, 'dropout1': 0.19492379978847293, 'dropout2': 0.1259373123876904, 'initializer': <keras.initializers.initializers.Orthogonal object at 0x0000020ACC5B2190>, 'layer1': 1415.0, 'layer2': 1252.0, 'layer3': 1485.0, 'layer4': 232.0, 'learning_rate': 0.0003013467240068926, 'TRIAL_BUDGET': 11, 'epochs': 1}\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Again define best_params\n",
    "with open(hyperparam_path) as json_file:\n",
    "    best_params = json.load(json_file)\n",
    "\n",
    "best_params[\"epochs\"] = 1\n",
    "best_params[\"initializer\"] = tf.keras.initializers.Orthogonal()\n",
    "for name in [\"layer1\",\"layer2\",\"layer3\",\"layer4\"]:\n",
    "        best_params[name] = np.round(best_params[name])\n",
    "\n",
    "print(best_params)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "529cab0e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Env Config\n",
    "env_config = {\"action_space_path\":action_set,\n",
    "              \"env_path\": env_path,\n",
    "              \"action_threshold\":0.95,\n",
    "              'filtered_obs':True,\n",
    "              'scaler': ray_scal,\n",
    "              'subset' : False\n",
    "              }\n",
    "\n",
    "# Model Config:\n",
    "model_config = {\"path_to_junior\":target,\n",
    "                \"custom_config\":best_params}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "Testing whether we can load the model. Then, we initialize the model config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c48f6374-e87b-4c08-ae7c-6df59a2f7f78",
   "metadata": {},
   "outputs": [],
   "source": [
    "from curriculumagent.senior.rllib_execution.senior_env_rllib import SeniorEnvRllib\n",
    "from curriculumagent.senior.rllib_execution.senior_model_rllib import Grid2OpCustomModel"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5e74eb2d-716c-418a-99a0-dade46d162e6",
   "metadata": {},
   "source": [
    "## Testing both the environment and the model\n",
    "\n",
    "Scip these methods if you want to start directly with the ray optimization.\n",
    "\n",
    "Note that you can check, whether your scaler works."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "84638335-7454-44e2-ab74-f58df731667b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_trafo.py:67: UserWarning: There were some Nan in the pp_net.trafo[\"tap_step_degree\"], they have been replaced by 0\n",
      "  warnings.warn(\"There were some Nan in the pp_net.trafo[\\\"tap_step_degree\\\"], they have been replaced by 0\")\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\lightsim2grid\\gridmodel\\_aux_add_slack.py:114: UserWarning: We found either some slack coefficient to be < 0. or they were all 0.We set them all to 1.0 to avoid such issues\n",
      "  warnings.warn(\"We found either some slack coefficient to be < 0. or they were all 0.\"\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: divide by zero encountered in divide\n",
      "  p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1848: RuntimeWarning: invalid value encountered in multiply\n",
      "  p_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: divide by zero encountered in divide\n",
      "  q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n",
      "c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\grid2op\\Backend\\backend.py:1849: RuntimeWarning: invalid value encountered in multiply\n",
      "  q_s[sh_conn] *= (self._sh_vnkv[sh_conn] / sh_v[sh_conn]) ** 2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "806\n",
      "(1429,)\n"
     ]
    }
   ],
   "source": [
    "# Test Environment:\n",
    "env =  SeniorEnvRllib(env_config)\n",
    "print(env.action_space.n)\n",
    "print(env.observation_space.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "0f743f2f",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "too many values to unpack (expected 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[16], line 5\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m done\u001b[38;5;241m==\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m:\n\u001b[0;32m      4\u001b[0m     act \u001b[38;5;241m=\u001b[39m random\u001b[38;5;241m.\u001b[39mchoice(np\u001b[38;5;241m.\u001b[39marange(env\u001b[38;5;241m.\u001b[39maction_space\u001b[38;5;241m.\u001b[39mn))\n\u001b[1;32m----> 5\u001b[0m     obs,b,done,d \u001b[38;5;241m=\u001b[39m env\u001b[38;5;241m.\u001b[39mstep(act)\n\u001b[0;32m      6\u001b[0m     \u001b[38;5;28mprint\u001b[39m(act,done,b,env\u001b[38;5;241m.\u001b[39mstep_in_env,\u001b[38;5;28mmax\u001b[39m(obs),\u001b[38;5;28mmin\u001b[39m(obs),env\u001b[38;5;241m.\u001b[39msingle_env\u001b[38;5;241m.\u001b[39mnb_time_step)\n",
      "\u001b[1;31mValueError\u001b[0m: too many values to unpack (expected 4)"
     ]
    }
   ],
   "source": [
    "\n",
    "# Run \"simulation\":\n",
    "done = False\n",
    "while done==False:\n",
    "    act = random.choice(np.arange(env.action_space.n))\n",
    "    obs,b,done,d = env.step(act)\n",
    "    print(act,done,b,env.step_in_env,max(obs),min(obs),env.single_env.nb_time_step)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "model:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "<keras.initializers.initializers.Orthogonal object at 0x0000020ACC5B2190>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[17], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# Test Model:\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m model \u001b[38;5;241m=\u001b[39m \u001b[43mGrid2OpCustomModel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobs_space\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43menv\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mobservation_space\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      3\u001b[0m \u001b[43m                           \u001b[49m\u001b[43maction_space\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43menv\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43maction_space\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      4\u001b[0m \u001b[43m                           \u001b[49m\u001b[43mnum_outputs\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43menv\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43maction_space\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      5\u001b[0m \u001b[43m                           \u001b[49m\u001b[43mmodel_config\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43m{\u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      6\u001b[0m \u001b[43m                           \u001b[49m\u001b[43mpath_to_junior\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtarget\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      7\u001b[0m \u001b[43m                           \u001b[49m\u001b[43mcustom_config\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mbest_params\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m      8\u001b[0m \u001b[43m                           \u001b[49m\u001b[43mname\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mJunior\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m      9\u001b[0m \u001b[38;5;28mprint\u001b[39m(model\u001b[38;5;241m.\u001b[39mbase_model\u001b[38;5;241m.\u001b[39msummary())\n\u001b[0;32m     10\u001b[0m obs_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mobs\u001b[39m\u001b[38;5;124m\"\u001b[39m: obs\u001b[38;5;241m.\u001b[39mreshape(\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m)}\n",
      "File \u001b[1;32mc:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\curriculumagent\\senior\\rllib_execution\\senior_model_rllib.py:50\u001b[0m, in \u001b[0;36mGrid2OpCustomModel.__init__\u001b[1;34m(self, obs_space, action_space, num_outputs, model_config, name, **customized_model_kwargs)\u001b[0m\n\u001b[0;32m     48\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m     49\u001b[0m     cconfig \u001b[38;5;241m=\u001b[39m {}\n\u001b[1;32m---> 50\u001b[0m layer_size, initializer, activation \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_extract_config\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcconfig\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     52\u001b[0m \u001b[38;5;66;03m# Now Init model:\u001b[39;00m\n\u001b[0;32m     53\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39minputs \u001b[38;5;241m=\u001b[39m tf\u001b[38;5;241m.\u001b[39mkeras\u001b[38;5;241m.\u001b[39mlayers\u001b[38;5;241m.\u001b[39mInput(shape\u001b[38;5;241m=\u001b[39mobs_space\u001b[38;5;241m.\u001b[39mshape, name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mobservations\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\curriculumagent\\senior\\rllib_execution\\senior_model_rllib.py:120\u001b[0m, in \u001b[0;36mGrid2OpCustomModel._extract_config\u001b[1;34m(self, config)\u001b[0m\n\u001b[0;32m    117\u001b[0m     activation \u001b[38;5;241m=\u001b[39m activation_option[config[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mactivation\u001b[39m\u001b[38;5;124m\"\u001b[39m]]\n\u001b[0;32m    119\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minitializer\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m config\u001b[38;5;241m.\u001b[39mkeys():\n\u001b[1;32m--> 120\u001b[0m     initializer \u001b[38;5;241m=\u001b[39m \u001b[43minitializer_option\u001b[49m\u001b[43m[\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43minitializer\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m]\u001b[49m\n\u001b[0;32m    122\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mall\u001b[39m([l \u001b[38;5;129;01min\u001b[39;00m config\u001b[38;5;241m.\u001b[39mkeys() \u001b[38;5;28;01mfor\u001b[39;00m l \u001b[38;5;129;01min\u001b[39;00m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer1\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer2\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer3\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer4\u001b[39m\u001b[38;5;124m\"\u001b[39m]]):\n\u001b[0;32m    123\u001b[0m     layer_size \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28mint\u001b[39m(np\u001b[38;5;241m.\u001b[39mround(config[l])) \u001b[38;5;28;01mfor\u001b[39;00m l \u001b[38;5;129;01min\u001b[39;00m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer1\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer2\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer3\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlayer4\u001b[39m\u001b[38;5;124m\"\u001b[39m]]\n",
      "\u001b[1;31mKeyError\u001b[0m: <keras.initializers.initializers.Orthogonal object at 0x0000020ACC5B2190>"
     ]
    }
   ],
   "source": [
    "# Test Model:\n",
    "model = Grid2OpCustomModel(obs_space = env.observation_space,\n",
    "                           action_space = env.action_space,\n",
    "                           num_outputs = env.action_space.n,\n",
    "                           model_config = {},\n",
    "                           path_to_junior =target,\n",
    "                           custom_config = best_params,\n",
    "                           name=\"Junior\")\n",
    "print(model.base_model.summary())\n",
    "obs_dict = {\"obs\": obs.reshape(1,-1)}\n",
    "out = model.forward(input_dict = obs_dict, state=1, seq_lens=None)\n",
    "out"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "344e78ef-9186-4fbd-9840-4b3c8573a87c",
   "metadata": {},
   "source": [
    "## Run Rllib experiment to collect the Senior Model\n",
    "\n",
    "We run the senior experiment. Please adjust the number of cpus, gpus and workers based on your computational power."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "8fa3bac1-4151-4192-a0b5-631f4af07cde",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Register the model\n",
    "ModelCatalog.register_custom_model('Senior',  Grid2OpCustomModel)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "2712945c-513d-434e-bbaf-30fa93f7f431",
   "metadata": {},
   "outputs": [],
   "source": [
    "NUM_WORKER = os.cpu_count() - 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "2f3e455b-8d4a-4e3b-989c-fcc2ba7c5988",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div class=\"tuneStatus\">\n",
       "  <div style=\"display: flex;flex-direction: row\">\n",
       "    <div style=\"display: flex;flex-direction: column;\">\n",
       "      <h3>Tune Status</h3>\n",
       "      <table>\n",
       "<tbody>\n",
       "<tr><td>Current time:</td><td>2024-05-06 15:37:09</td></tr>\n",
       "<tr><td>Running for: </td><td>00:03:28.31        </td></tr>\n",
       "<tr><td>Memory:      </td><td>14.3/14.8 GiB      </td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "    <div class=\"systemInfo\">\n",
       "      <h3>System Info</h3>\n",
       "      PopulationBasedTraining: 0 checkpoints, 0 perturbs<br>Logical resource usage: 16.0/16 CPUs, 0/0 GPUs\n",
       "    </div>\n",
       "    <div class=\"vDivider\"></div>\n",
       "<div class=\"messages\">\n",
       "  <h3>Messages</h3>\n",
       "  : ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.\n",
       "  \n",
       "  Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                    </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                   </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_SeniorEnvRllib_409f2_00000</td><td style=\"text-align: right;\">           2</td><td>C:\\Users\\thoma\\ray_results\\PPO\\PPO_SeniorEnvRllib_409f2_00000_0_2024-05-06_15-33-41\\error.txt</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "</div>\n",
       "<style>\n",
       ".messages {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  padding-left: 1em;\n",
       "  overflow-y: auto;\n",
       "}\n",
       ".messages h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n",
       "\n",
       "  </div>\n",
       "  <div class=\"hDivider\"></div>\n",
       "  <div class=\"trialStatus\">\n",
       "    <h3>Trial Status</h3>\n",
       "    <table>\n",
       "<thead>\n",
       "<tr><th>Trial name                    </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  clip_param</th><th style=\"text-align: right;\">  entropy_coeff</th><th style=\"text-align: right;\">   gamma</th><th style=\"text-align: right;\">  num_sgd_iter</th><th style=\"text-align: right;\">  vf_loss_coeff</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_SeniorEnvRllib_409f2_00000</td><td>PENDING </td><td>     </td><td style=\"text-align: right;\">     0.31736</td><td style=\"text-align: right;\">    2.08045e-05</td><td style=\"text-align: right;\">0.978481</td><td style=\"text-align: right;\">             4</td><td style=\"text-align: right;\">       0.501743</td></tr>\n",
       "</tbody>\n",
       "</table>\n",
       "  </div>\n",
       "</div>\n",
       "<style>\n",
       ".tuneStatus {\n",
       "  color: var(--jp-ui-font-color1);\n",
       "}\n",
       ".tuneStatus .systemInfo {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus td {\n",
       "  white-space: nowrap;\n",
       "}\n",
       ".tuneStatus .trialStatus {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       ".tuneStatus h3 {\n",
       "  font-weight: bold;\n",
       "}\n",
       ".tuneStatus .hDivider {\n",
       "  border-bottom-width: var(--jp-border-width);\n",
       "  border-bottom-color: var(--jp-border-color0);\n",
       "  border-bottom-style: solid;\n",
       "}\n",
       ".tuneStatus .vDivider {\n",
       "  border-left-width: var(--jp-border-width);\n",
       "  border-left-color: var(--jp-border-color0);\n",
       "  border-left-style: solid;\n",
       "  margin: 0.5em 1em 0.5em 1em;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-06 15:35:03,707\tERROR tune_controller.py:873 -- Trial task failed for trial PPO_SeniorEnvRllib_409f2_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\worker.py\", line 2542, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::PPO.__init__()\u001b[39m (pid=28980, ip=127.0.0.1, actor_id=b3aa8c21880e0ac687c1036101000000, repr=PPO)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 242, in _setup\n",
      "    self.add_workers(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 635, in add_workers\n",
      "    raise result.get()\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 488, in __fetch_result\n",
      "    result = ray.get(r)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\worker.py\", line 2542, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=19080, ip=127.0.0.1, actor_id=881f7bf2122de0001353ec3701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000206C20E02B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 738, in __init__\n",
      "    self._update_policy_map(policy_dict=self.policy_dict)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\n",
      "    self._build_policy_map(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\n",
      "    new_policy = create_policy_for_framework(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\n",
      "    return policy_class(observation_space, action_space, merged_config)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\ppo\\ppo_torch_policy.py\", line 49, in __init__\n",
      "    TorchPolicyV2.__init__(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\n",
      "    model, dist_class = self._init_model_and_dist_class()\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\n",
      "    model = ModelCatalog.get_model_v2(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\n",
      "    model_cls = _global_registry.get(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\n",
      "    raise ValueError(\n",
      "ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::PPO.__init__()\u001b[39m (pid=28980, ip=127.0.0.1, actor_id=b3aa8c21880e0ac687c1036101000000, repr=PPO)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1431, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1510, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 475, in __init__\n",
      "    super().__init__(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 170, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 601, in setup\n",
      "    self.workers = WorkerSet(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 194, in __init__\n",
      "    raise e.args[0].args[2]\n",
      "ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "2024-05-06 15:36:13,971\tERROR tune_controller.py:873 -- Trial task failed for trial PPO_SeniorEnvRllib_409f2_00000\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\air\\execution\\_internal\\event_manager.py\", line 110, in resolve_future\n",
      "    result = ray.get(future)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\worker.py\", line 2542, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::PPO.__init__()\u001b[39m (pid=20508, ip=127.0.0.1, actor_id=b9b2c4d442914033cfa6895901000000, repr=PPO)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 242, in _setup\n",
      "    self.add_workers(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 635, in add_workers\n",
      "    raise result.get()\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py\", line 488, in __fetch_result\n",
      "    result = ray.get(r)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 18, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\worker.py\", line 2542, in get\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=21900, ip=127.0.0.1, actor_id=270ae72df27c84cb7d191e4d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A373A9F310>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 738, in __init__\n",
      "    self._update_policy_map(policy_dict=self.policy_dict)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 1985, in _update_policy_map\n",
      "    self._build_policy_map(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\rollout_worker.py\", line 2097, in _build_policy_map\n",
      "    new_policy = create_policy_for_framework(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\utils\\policy.py\", line 142, in create_policy_for_framework\n",
      "    return policy_class(observation_space, action_space, merged_config)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\ppo\\ppo_torch_policy.py\", line 49, in __init__\n",
      "    TorchPolicyV2.__init__(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 94, in __init__\n",
      "    model, dist_class = self._init_model_and_dist_class()\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\policy\\torch_policy_v2.py\", line 488, in _init_model_and_dist_class\n",
      "    model = ModelCatalog.get_model_v2(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\models\\catalog.py\", line 478, in get_model_v2\n",
      "    model_cls = _global_registry.get(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\registry.py\", line 267, in get\n",
      "    raise ValueError(\n",
      "ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::PPO.__init__()\u001b[39m (pid=20508, ip=127.0.0.1, actor_id=b9b2c4d442914033cfa6895901000000, repr=PPO)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1431, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1510, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1434, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1438, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1378, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 724, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 475, in __init__\n",
      "    super().__init__(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py\", line 170, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py\", line 601, in setup\n",
      "    self.workers = WorkerSet(\n",
      "  File \"c:\\Users\\thoma\\anaconda3\\envs\\MA1\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py\", line 194, in __init__\n",
      "    raise e.args[0].args[2]\n",
      "ValueError: Registry value for rllib_model/binbinchen doesn't exist.\n",
      "2024-05-06 15:37:09,664\tWARNING tune.py:192 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. \n",
      "2024-05-06 15:37:09,683\tWARNING tune.py:1085 -- Trial Runner checkpointing failed: Sync process failed: GetFileInfo() yielded path 'C:/Users/thoma/ray_results/PPO', which is outside base dir 'C:\\Users\\thoma\\ray_results\\PPO'\n",
      "2024-05-06 15:37:20,126\tINFO tune.py:1111 -- Total run time: 219.23 seconds (208.29 seconds for the tuning loop).\n",
      "2024-05-06 15:37:20,139\tWARNING tune.py:1126 -- Experiment has been interrupted, but the most recent state was saved.\n",
      "Resume experiment with: tune.run(..., resume=True)\n",
      "2024-05-06 15:37:20,795\tWARNING experiment_analysis.py:910 -- Failed to read the results for 1 trials:\n",
      "- C:\\Users\\thoma\\ray_results\\PPO\\PPO_SeniorEnvRllib_409f2_00000_0_2024-05-06_15-33-41\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<ray.tune.analysis.experiment_analysis.ExperimentAnalysis at 0x20a875ab700>"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pbt = PopulationBasedTraining(\n",
    "        time_attr=\"training_iteration\",\n",
    "        metric=\"episode_reward_mean\",\n",
    "        mode=\"max\",\n",
    "        perturbation_interval=50,\n",
    "        resample_probability=0.5,\n",
    "        # Specifies the mutations of these hyperparams\n",
    "        hyperparam_mutations={\n",
    "            \"lr\": [1e-3, 5e-4, 1e-4, 5e-5, 1e-5],\n",
    "            \"num_sgd_iter\": lambda: random.randint(3, 10),\n",
    "            \"vf_loss_coeff\": lambda: random.uniform(0.5,1),\n",
    "            \"clip_param\": lambda: random.uniform(0.01, 0.5),\n",
    "            \"gamma\": lambda: random.uniform(0.975, 1),\n",
    "            \"entropy_coeff\": lambda: 10**-random.uniform(2,5)\n",
    "        })\n",
    "\n",
    "tune.run(\n",
    "    \"PPO\",\n",
    "    checkpoint_freq=5,\n",
    "    scheduler= pbt,\n",
    "    keep_checkpoints_num =30, \n",
    "    verbose = 1,\n",
    "    max_failures=3, \n",
    "    num_samples=1,\n",
    "    local_dir=\"~/ray_results\",\n",
    "    stop={\"training_iteration\": 1},\n",
    "    config={\n",
    "        \"env\":  SeniorEnvRllib,\n",
    "        \"env_config\":env_config,\n",
    "        \"num_workers\":NUM_WORKER,\n",
    "        \"num_envs_per_worker\": 1,\n",
    "        \"lr\": 5e-5,\n",
    "        \"num_gpus\":0.0,\n",
    "        \"num_cpus_per_worker\": 1,\n",
    "        \"remote_worker_envs\": False,\n",
    "        \"model\":{\"custom_model\":  \"binbinchen\",\"custom_model_config\": model_config},\n",
    "    },\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24710678-e238-408a-98c5-429075ef24c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "isinstance(ray_scal,ray._raylet.ObjectRef)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f008dbe-c300-47f3-803a-aa1a8e3cce1d",
   "metadata": {},
   "source": [
    "## Select and convert checkpoint\n",
    "\n",
    "After the training is completed, one to collect the saved model\n",
    "\n",
    "Note, you have to specify the correct checkpoint dir in ```\"~/ray_results\"```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from curriculumagent.senior.rllib_execution.convert_rllib_ckpt import load_config,load_and_save_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "example_dir = \"/ray_results/PPO/PPO_SeniorEnvRllib_6c729_00001_1_2022-04-06_15-28-19\"\n",
    "ckpt_path = Path(example_dir) / \"checkpoint_000675\"/\"checkpoint-675\"\n",
    "save_path =  Path(example_path) /\"senior_model\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "First we load the config of the ray experiment and overwrite the class values with the actual classes:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "config = load_config(ckpt_path)\n",
    "config['env_config'] = env_config\n",
    "config[\"model\"]['custom_model_config']['custom_config'] = model_config"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "Now run and save the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99b35f8c-9b1f-4ea0-9f12-946271ddc2c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "load_and_save_model(ckpt_path = ckpt_path,config =config, save_path = save_path, ckpt_nr = 675)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## Submission:\n",
    "\n",
    "In order to correctly submit a working agent, the tensorflow model now only needs to be placed in a submission\n",
    "folder, together with the action set. An example can be found in ```my_agent_advanced.py```"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
